#include <iostream>
#include <list>
#include <vector>
#include <unordered_map>

//#include <GL/glew.h>
#include <GLFW/glfw3.h>

using namespace std;

struct List
{
    size_t size;
    void* data;
};

#define VAR(x) int VAR_ ## x = x

extern "C"
{
    int EVENT_KEYDOWN = 0;
    int EVENT_KEYUP = 1;

    VAR(GLFW_RESIZABLE);
    VAR(GLFW_VISIBLE);
    VAR(GLFW_DECORATED);
    VAR(GLFW_FOCUSED);
    VAR(GLFW_AUTO_ICONIFY);
    VAR(GLFW_FLOATING);
    VAR(GLFW_MAXIMIZED);
    VAR(GLFW_CENTER_CURSOR);
    VAR(GLFW_TRANSPARENT_FRAMEBUFFER);
    VAR(GLFW_FOCUS_ON_SHOW);
    VAR(GLFW_SCALE_TO_MONITOR);
    VAR(GLFW_SCALE_FRAMEBUFFER);
    VAR(GLFW_MOUSE_PASSTHROUGH);
    VAR(GLFW_POSITION_X);
    VAR(GLFW_POSITION_Y);
    VAR(GLFW_RED_BITS);
    VAR(GLFW_GREEN_BITS);
    VAR(GLFW_BLUE_BITS);
    VAR(GLFW_ALPHA_BITS);
    VAR(GLFW_DEPTH_BITS);
    VAR(GLFW_STENCIL_BITS);
    VAR(GLFW_ACCUM_RED_BITS);
    VAR(GLFW_ACCUM_GREEN_BITS);
    VAR(GLFW_ACCUM_BLUE_BITS);
    VAR(GLFW_ACCUM_ALPHA_BITS);
    VAR(GLFW_AUX_BUFFERS);
    VAR(GLFW_SAMPLES);
    VAR(GLFW_REFRESH_RATE);
    VAR(GLFW_STEREO);
    VAR(GLFW_SRGB_CAPABLE);
    VAR(GLFW_DOUBLEBUFFER);
    VAR(GLFW_CLIENT_API);
    VAR(GLFW_CONTEXT_CREATION_API);
    VAR(GLFW_CONTEXT_VERSION_MAJOR);
    VAR(GLFW_CONTEXT_VERSION_MINOR);
    VAR(GLFW_CONTEXT_ROBUSTNESS);
    VAR(GLFW_CONTEXT_RELEASE_BEHAVIOR);
    VAR(GLFW_OPENGL_FORWARD_COMPAT);
    VAR(GLFW_CONTEXT_DEBUG);
    VAR(GLFW_OPENGL_PROFILE);
    VAR(GLFW_WIN32_KEYBOARD_MENU);
    VAR(GLFW_WIN32_SHOWDEFAULT);
    VAR(GLFW_COCOA_FRAME_NAME);
    VAR(GLFW_COCOA_GRAPHICS_SWITCHING);
    VAR(GLFW_WAYLAND_APP_ID);
    VAR(GLFW_X11_CLASS_NAME);
    VAR(GLFW_X11_INSTANCE_NAME);

    VAR(GLFW_KEY_SPACE);
    VAR(GLFW_KEY_APOSTROPHE);
    VAR(GLFW_KEY_COMMA);
    VAR(GLFW_KEY_MINUS);
    VAR(GLFW_KEY_PERIOD);
    VAR(GLFW_KEY_SLASH);
    VAR(GLFW_KEY_0);
    VAR(GLFW_KEY_1);
    VAR(GLFW_KEY_2);
    VAR(GLFW_KEY_3);
    VAR(GLFW_KEY_4);
    VAR(GLFW_KEY_9);
    VAR(GLFW_KEY_SEMICOLON);
    VAR(GLFW_KEY_EQUAL);
    VAR(GLFW_KEY_A);
    VAR(GLFW_KEY_B);
    VAR(GLFW_KEY_C);
    VAR(GLFW_KEY_D);
    VAR(GLFW_KEY_E);
    VAR(GLFW_KEY_F);
    VAR(GLFW_KEY_G);
    VAR(GLFW_KEY_H);
    VAR(GLFW_KEY_I);
    VAR(GLFW_KEY_J);
    VAR(GLFW_KEY_K);
    VAR(GLFW_KEY_L);
    VAR(GLFW_KEY_M);
    VAR(GLFW_KEY_N);
    VAR(GLFW_KEY_O);
    VAR(GLFW_KEY_P);
    VAR(GLFW_KEY_Q);
    VAR(GLFW_KEY_R);
    VAR(GLFW_KEY_S);
    VAR(GLFW_KEY_T);
    VAR(GLFW_KEY_U);
    VAR(GLFW_KEY_V);
    VAR(GLFW_KEY_W);
    VAR(GLFW_KEY_X);
    VAR(GLFW_KEY_Y);
    VAR(GLFW_KEY_Z);
    VAR(GLFW_KEY_LEFT_BRACKET);
    VAR(GLFW_KEY_BACKSLASH);
    VAR(GLFW_KEY_RIGHT_BRACKET);
    VAR(GLFW_KEY_GRAVE_ACCENT);
    VAR(GLFW_KEY_WORLD_1);
    VAR(GLFW_KEY_WORLD_2);
    VAR(GLFW_KEY_ESCAPE);
    VAR(GLFW_KEY_ENTER);
    VAR(GLFW_KEY_TAB);
    VAR(GLFW_KEY_BACKSPACE);
    VAR(GLFW_KEY_INSERT);
    VAR(GLFW_KEY_DELETE);
    VAR(GLFW_KEY_RIGHT);
    VAR(GLFW_KEY_LEFT);
    VAR(GLFW_KEY_DOWN);
    VAR(GLFW_KEY_UP);
    VAR(GLFW_KEY_PAGE_UP);
    VAR(GLFW_KEY_PAGE_DOWN);
    VAR(GLFW_KEY_HOME);
    VAR(GLFW_KEY_END);
    VAR(GLFW_KEY_CAPS_LOCK);
    VAR(GLFW_KEY_SCROLL_LOCK);
    VAR(GLFW_KEY_NUM_LOCK);
    VAR(GLFW_KEY_PRINT_SCREEN);
    VAR(GLFW_KEY_PAUSE);
    VAR(GLFW_KEY_F1);
    VAR(GLFW_KEY_F2);
    VAR(GLFW_KEY_F3);
    VAR(GLFW_KEY_F4);
    VAR(GLFW_KEY_F5);
    VAR(GLFW_KEY_F6);
    VAR(GLFW_KEY_F7);
    VAR(GLFW_KEY_F8);
    VAR(GLFW_KEY_F9);
    VAR(GLFW_KEY_F10);
    VAR(GLFW_KEY_F11);
    VAR(GLFW_KEY_F12);
    VAR(GLFW_KEY_F13);
    VAR(GLFW_KEY_F14);
    VAR(GLFW_KEY_F15);
    VAR(GLFW_KEY_F16);
    VAR(GLFW_KEY_F17);
    VAR(GLFW_KEY_F18);
    VAR(GLFW_KEY_F19);
    VAR(GLFW_KEY_F20);
    VAR(GLFW_KEY_F21);
    VAR(GLFW_KEY_F22);
    VAR(GLFW_KEY_F23);
    VAR(GLFW_KEY_F24);
    VAR(GLFW_KEY_F25);
    VAR(GLFW_KEY_KP_0);
    VAR(GLFW_KEY_KP_1);
    VAR(GLFW_KEY_KP_2);
    VAR(GLFW_KEY_KP_3);
    VAR(GLFW_KEY_KP_4);
    VAR(GLFW_KEY_KP_5);
    VAR(GLFW_KEY_KP_6);
    VAR(GLFW_KEY_KP_7);
    VAR(GLFW_KEY_KP_8);
    VAR(GLFW_KEY_KP_9);
    VAR(GLFW_KEY_KP_DECIMAL);
    VAR(GLFW_KEY_KP_DIVIDE);
    VAR(GLFW_KEY_KP_MULTIPLY);
    VAR(GLFW_KEY_KP_SUBTRACT);
    VAR(GLFW_KEY_KP_ADD);
    VAR(GLFW_KEY_KP_ENTER);
    VAR(GLFW_KEY_KP_EQUAL);
    VAR(GLFW_KEY_LEFT_SHIFT);
    VAR(GLFW_KEY_LEFT_CONTROL);
    VAR(GLFW_KEY_LEFT_ALT);
    VAR(GLFW_KEY_LEFT_SUPER);
    VAR(GLFW_KEY_RIGHT_SHIFT);
    VAR(GLFW_KEY_RIGHT_CONTROL);
    VAR(GLFW_KEY_RIGHT_ALT);
    VAR(GLFW_KEY_RIGHT_SUPER);
    VAR(GLFW_KEY_MENU);
    VAR(GLFW_KEY_LAST);

    VAR(GLFW_MOD_SHIFT);
    VAR(GLFW_MOD_CONTROL);
    VAR(GLFW_MOD_ALT);
    VAR(GLFW_MOD_SUPER);
    VAR(GLFW_MOD_CAPS_LOCK);
    VAR(GLFW_MOD_NUM_LOCK);
}

