#include <iostream>

//#include <GL/glew.h>
#include <GLFW/glfw3.h>

using namespace std;

#define VAR(x) int VAR_##x = x

extern "C"
{
    VAR(GLFW_RESIZABLE);
    VAR(GLFW_VISIBLE);
    VAR(GLFW_DECORATED);
    VAR(GLFW_FOCUSED);
    VAR(GLFW_AUTO_ICONIFY);
    VAR(GLFW_FLOATING);
    VAR(GLFW_MAXIMIZED);
    VAR(GLFW_CENTER_CURSOR);
    VAR(GLFW_TRANSPARENT_FRAMEBUFFER);
    VAR(GLFW_FOCUS_ON_SHOW);
    VAR(GLFW_SCALE_TO_MONITOR);
    VAR(GLFW_SCALE_FRAMEBUFFER);
    VAR(GLFW_MOUSE_PASSTHROUGH);
    VAR(GLFW_POSITION_X);
    VAR(GLFW_POSITION_Y);
    VAR(GLFW_RED_BITS);
    VAR(GLFW_GREEN_BITS);
    VAR(GLFW_BLUE_BITS);
    VAR(GLFW_ALPHA_BITS);
    VAR(GLFW_DEPTH_BITS);
    VAR(GLFW_STENCIL_BITS);
    VAR(GLFW_ACCUM_RED_BITS);
    VAR(GLFW_ACCUM_GREEN_BITS);
    VAR(GLFW_ACCUM_BLUE_BITS);
    VAR(GLFW_ACCUM_ALPHA_BITS);
    VAR(GLFW_AUX_BUFFERS);
    VAR(GLFW_SAMPLES);
    VAR(GLFW_REFRESH_RATE);
    VAR(GLFW_STEREO);
    VAR(GLFW_SRGB_CAPABLE);
    VAR(GLFW_DOUBLEBUFFER);
    VAR(GLFW_CLIENT_API);
    VAR(GLFW_CONTEXT_CREATION_API);
    VAR(GLFW_CONTEXT_VERSION_MAJOR);
    VAR(GLFW_CONTEXT_VERSION_MINOR);
    VAR(GLFW_CONTEXT_ROBUSTNESS);
    VAR(GLFW_CONTEXT_RELEASE_BEHAVIOR);
    VAR(GLFW_OPENGL_FORWARD_COMPAT);
    VAR(GLFW_CONTEXT_DEBUG);
    VAR(GLFW_OPENGL_PROFILE);
    VAR(GLFW_WIN32_KEYBOARD_MENU);
    VAR(GLFW_WIN32_SHOWDEFAULT);
    VAR(GLFW_COCOA_FRAME_NAME);
    VAR(GLFW_COCOA_GRAPHICS_SWITCHING);
    VAR(GLFW_WAYLAND_APP_ID);
    VAR(GLFW_X11_CLASS_NAME);
    VAR(GLFW_X11_INSTANCE_NAME);
}

