#include <iostream>

//#include <GL/glew.h>
#include <GLFW/glfw3.h>

using namespace std;

#define VAR(x) int x = x

extern "C"
{
    VAR(GLFW_RESIZABLE);
    VAR(GLFW_VISIBLE);
    VAR(GLFW_DECORATED);
    VAR(GLFW_FOCUSED);
    VAR(GLFW_AUTO_ICONIFY);
    VAR(GLFW_FLOATING);
    VAR(GLFW_MAXIMIZED);
    VAR(GLFW_CENTER_CURSOR);
    VAR(GLFW_TRANSPARENT_FRAMEBUFFER);
    VAR(GLFW_FOCUS_ON_SHOW);
    VAR(GLFW_SCALE_TO_MONITOR);
    VAR(GLFW_SCALE_FRAMEBUFFER);
    VAR(GLFW_MOUSE_PASSTHROUGH);
    VAR(GLFW_POSITION_X);
    VAR(GLFW_POSITION_Y);
}

